# Generated by Django 4.0.8 on 2023-10-28 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ingredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_description', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='images_db')),
                ('recipe_view_count', models.IntegerField(default=0)),
                ('recipe_hardness', models.CharField(max_length=100)),
                ('recipe_time', models.IntegerField(blank=True, default=60, null=True)),
                ('recipe_cuisine', models.TextField(blank=True, null=True, verbose_name=recipeapp.models.cuisine)),
                ('recipe_ingredient', models.ManyToManyField(blank=True, null=True, to='recipeapp.ingredientitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
