# Generated by Django 4.0.8 on 2023-10-28 17:38

from django.db import migrations, models
import recipeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredientitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_cuisine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=recipeapp.models.cuisine),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.ManyToManyField(blank=True, to='recipeapp.ingredientitem'),
        ),
    ]
