# Generated by Django 4.0.8 on 2023-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_alter_recipe_recipe_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_private',
            field=models.BooleanField(default=False),
        ),
    ]
